### ISSUE TITLE
Puede resultar confuso crear una clase con el mismo nombre del tag.

### ISSUE THREAD

**Issue by itacademyReact** [Olivermusico/React#1]
Puedes estilizar directamente el tag section en lugar de crear una clase para ello:

section {
  ...
}

https://github.com/Olivermusico/React/blob/f73372fabf55cf515a31516e343bb59b63e58b9a/Sprint-1/nivell-1/index.html#L29

**Comment by Olivermusico** [comment]
Perfect. lo he cambiado al nivel 2.
